CREATE TABLE public.redeem_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    reward_credits INT NOT NULL,
    max_redemptions INT NOT NULL,
    redeemed_count INT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    starts_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT redeem_codes_code_not_blank_check CHECK (NULLIF(trim(code), '') IS NOT NULL),
    CONSTRAINT redeem_codes_code_uppercase_check CHECK (code = upper(code)),
    CONSTRAINT redeem_codes_reward_credits_check CHECK (reward_credits > 0),
    CONSTRAINT redeem_codes_max_redemptions_check CHECK (max_redemptions > 0),
    CONSTRAINT redeem_codes_redeemed_count_check CHECK (redeemed_count >= 0),
    CONSTRAINT redeem_codes_redeemed_count_limit_check CHECK (redeemed_count <= max_redemptions),
    CONSTRAINT redeem_codes_time_window_check CHECK (starts_at IS NULL OR expires_at IS NULL OR starts_at < expires_at)
);

CREATE TABLE public.redeem_code_redemptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    redeem_code_id BIGINT NOT NULL REFERENCES public.redeem_codes(id) ON DELETE RESTRICT,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    reward_credits INT NOT NULL,
    redeemed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT redeem_code_redemptions_reward_credits_check CHECK (reward_credits > 0),
    CONSTRAINT redeem_code_redemptions_unique_user_code UNIQUE (redeem_code_id, user_id)
);

CREATE INDEX redeem_code_redemptions_user_id_redeemed_at_idx
    ON public.redeem_code_redemptions (user_id, redeemed_at DESC);

CREATE TRIGGER handle_redeem_codes_updated_at
    BEFORE UPDATE ON public.redeem_codes
    FOR EACH ROW
    EXECUTE FUNCTION extensions.moddatetime(updated_at);

ALTER TABLE public.redeem_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.redeem_code_redemptions ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.redeem_code_for_current_user(p_code TEXT)
RETURNS TABLE (
    ok BOOLEAN,
    code TEXT,
    message TEXT,
    reward_credits INT,
    credits INT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_user_id UUID := auth.uid();
    v_input_code TEXT := upper(trim(coalesce(p_code, '')));
    v_now TIMESTAMPTZ := NOW();
    v_redeem_code public.redeem_codes;
    v_credits INT;
BEGIN
    IF v_user_id IS NULL THEN
        RETURN QUERY
        SELECT false, 'UNAUTHORIZED', 'User is not authenticated', NULL::INT, NULL::INT;
        RETURN;
    END IF;

    IF v_input_code = '' THEN
        RETURN QUERY
        SELECT false, 'CODE_NOT_FOUND', 'Redeem code not found', NULL::INT, NULL::INT;
        RETURN;
    END IF;

    SELECT *
    INTO v_redeem_code
    FROM public.redeem_codes
    WHERE redeem_codes.code = v_input_code
    FOR UPDATE;

    IF NOT FOUND THEN
        RETURN QUERY
        SELECT false, 'CODE_NOT_FOUND', 'Redeem code not found', NULL::INT, NULL::INT;
        RETURN;
    END IF;

    IF NOT v_redeem_code.is_active THEN
        RETURN QUERY
        SELECT false, 'CODE_INACTIVE', 'Redeem code is inactive', NULL::INT, NULL::INT;
        RETURN;
    END IF;

    IF v_redeem_code.starts_at IS NOT NULL AND v_now < v_redeem_code.starts_at THEN
        RETURN QUERY
        SELECT false, 'CODE_NOT_STARTED', 'Redeem code is not active yet', NULL::INT, NULL::INT;
        RETURN;
    END IF;

    IF v_redeem_code.expires_at IS NOT NULL AND v_now >= v_redeem_code.expires_at THEN
        RETURN QUERY
        SELECT false, 'CODE_EXPIRED', 'Redeem code has expired', NULL::INT, NULL::INT;
        RETURN;
    END IF;

    IF v_redeem_code.redeemed_count >= v_redeem_code.max_redemptions THEN
        RETURN QUERY
        SELECT false, 'CODE_LIMIT_REACHED', 'Redeem code limit reached', NULL::INT, NULL::INT;
        RETURN;
    END IF;

    INSERT INTO public.billings (user_id)
    VALUES (v_user_id)
    ON CONFLICT (user_id) DO NOTHING;

    PERFORM public.refresh_daily_credits(v_user_id);

    BEGIN
        INSERT INTO public.redeem_code_redemptions (
            redeem_code_id,
            user_id,
            reward_credits
        )
        VALUES (
            v_redeem_code.id,
            v_user_id,
            v_redeem_code.reward_credits
        );
    EXCEPTION
        WHEN unique_violation THEN
            RETURN QUERY
            SELECT false, 'ALREADY_REDEEMED', 'Redeem code already redeemed by this user', NULL::INT, NULL::INT;
            RETURN;
    END;

    UPDATE public.redeem_codes
    SET redeemed_count = redeemed_count + 1
    WHERE id = v_redeem_code.id;

    UPDATE public.billings
    SET credits = billings.credits + v_redeem_code.reward_credits
    WHERE billings.user_id = v_user_id
    RETURNING billings.credits INTO v_credits;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Billing state not found for user %', v_user_id;
    END IF;

    RETURN QUERY
    SELECT true, NULL::TEXT, NULL::TEXT, v_redeem_code.reward_credits, v_credits;
END;
$$;

REVOKE ALL ON TABLE public.redeem_codes FROM PUBLIC;
REVOKE ALL ON TABLE public.redeem_code_redemptions FROM PUBLIC;
REVOKE ALL ON FUNCTION public.redeem_code_for_current_user(TEXT) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.redeem_code_for_current_user(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.redeem_code_for_current_user(TEXT) TO service_role;
