export const zhSlides = [
  {
    index: "01",
    title: "心有微澜\n星海赠你温柔的回响",
    image: "starsea",
    align: "right",
    accent: "mist",
    pose: "tilt",
  },
  {
    index: "02",
    title: "写下细微情绪\n在对话中\n读懂真实的自己",
    image: "glimmer",
    align: "left",
    accent: "silver",
    pose: "straight",
  },
  {
    index: "03",
    title: "安顿思绪\n留存你心灵\n成长的轨迹",
    image: "haven",
    align: "right",
    accent: "mist",
    pose: "tilt",
  },
  {
    index: "04",
    title: "翻开一页\n触碰人类最伟大的\n思想世界",
    image: "souler",
    align: "left",
    accent: "ember",
    pose: "straight",
  },
  {
    index: "05",
    title: "以第一视角\n亲历伟大灵魂的\n思想与挣扎",
    image: "chapter",
    align: "right",
    accent: "ember",
    pose: "tilt",
  },
];

export const enSlides = [
  {
    index: "01",
    title: "Every glimmer\nreceives a gentle\necho from Cosmos",
    image: "starsea",
    align: "right",
    accent: "mist",
    pose: "tilt",
  },
  {
    index: "02",
    title: "Write down thoughts\nto discover\nyour true self",
    image: "glimmer",
    align: "left",
    accent: "silver",
    pose: "straight",
  },
  {
    index: "03",
    title: "Settle your mind\nand preserve your\nspiritual journey",
    image: "haven",
    align: "right",
    accent: "mist",
    pose: "tilt",
  },
  {
    index: "04",
    title: "Explore a folio\nto touch history's\ngreatest minds",
    image: "souler",
    align: "left",
    accent: "ember",
    pose: "straight",
  },
  {
    index: "05",
    title: "Step in first-person\ninto their thoughts\nand struggles",
    image: "chapter",
    align: "right",
    accent: "ember",
    pose: "tilt",
  },
];
